package com.javacourse.examples.statictest;

public class BillingSystem {

    public String name;

    public Bill generateBill(int price){
        Bill result = new Bill();

        result.id = 1;
        result.date = "TODAY";
        result.value = price + (price * Bill.IVA);

        System.out.println("Bill generated by " + this.name);

        return result;
    }

    public static double quote(double price){
        return price + (price * Bill.IVA);
    }
}
